# 워크플로우의 이름
name: Hermes Stock Checker

on:
  # 5분마다 워크플로우를 실행 (cron 스케줄러)
  # GitHub Actions의 최소 간격은 5분입니다.
  schedule:
    - cron: '*/5 * * * *'
  # 수동 실행을 위한 버튼도 추가
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소의 코드를 가져옴
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 파이썬 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. requirements.txt에 명시된 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 파이썬 스크립트 실행
      # GitHub Secrets에 저장된 값들을 환경 변수로 전달
      - name: Run Python script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
